### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-2-evaluacion-intermedia-lilymenal#1]
Hola @lilymenal !!!

He visto que no te funciona la página porque se te enviaba siempre el formulario al no tener prevent default. Pero lo que tienes programado tiene muy buena pinta. Quieres terminar el ejercicio y luego te lo vuelvo a corregir?

Por cierto, esto me encanta: https://github.com/Adalab/modulo-2-evaluacion-intermedia-lilymenal/blob/master/Diagrama%20de%20flujo.jpg!!!!!!!!

**Comment by lilymenal** [comment]
Hola @migueldelmazo,
Muchas gracias, he actualizado la versión, perdona la tardanza.
Quedo pendiente a tus comentarios. #1
